/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ExamPaper } from './types.ts';

export interface CommunicationFormula {
  id: string;
  name: string;
  equation: string;
  variables: string;
  description: string;
  module: number;
}

export const bec402Formulas: CommunicationFormula[] = [
  {
    id: "shannon-hartley",
    name: "Shannon-Hartley Theorem",
    equation: "C = B * log₂(1 + SNR)",
    variables: "C = Channel Capacity (bps), B = Bandwidth (Hz), SNR = Signal-to-Noise ratio (linear value)",
    description: "Determines the theoretical maximum error-free data rate that can be transmitted over a noisy communication channel of a given bandwidth.",
    module: 4
  },
  {
    id: "am-mod-index",
    name: "Modulation Index (AM)",
    equation: "μ = (A_max - A_min) / (A_max + A_min)",
    variables: "μ = Modulation index, A_max = Maximum amplitude of envelope, A_min = Minimum amplitude of envelope",
    description: "A measure of the extent of amplitude variation in an AM wave. Standard range is between 0 and 1.",
    module: 2
  },
  {
    id: "am-total-power",
    name: "AM Wave Total Power",
    equation: "P_t = P_c * (1 + μ² / 2)",
    variables: "P_t = Total transmitted power, P_c = Carrier power, μ = Modulation index",
    description: "Expresses how the power is distributed in an AM wave. Single sideband power is given by P_c * μ² / 4.",
    module: 2
  },
  {
    id: "carsons-rule",
    name: "Carson's Rule (FM Bandwidth)",
    equation: "B_T = 2 * (Δf + f_m)",
    variables: "B_T = Transmission Bandwidth, Δf = Peak frequency deviation, f_m = Modulating frequency",
    description: "Provides an estimate for the transmission bandwidth required for wideband frequency-modulated (FM) signals.",
    module: 3
  },
  {
    id: "nyquist-rate",
    name: "Nyquist Rate (Sampling Theorem)",
    equation: "f_s = 2 * f_max",
    variables: "f_s = Minimum sampling rate (Hz), f_max = Highest frequency component of signal",
    description: "Specifies the minimum sampling frequency required to perfectly reconstruct a bandlimited analog signal without aliasing.",
    module: 4
  },
  {
    id: "pcm-snr",
    name: "PCM uniform quantizer (SNR)",
    equation: "(SNR)₀ = 1.76 + 6R  (in dB)",
    variables: "R = Number of bits per sample, (SNR)₀ = Output Signal-to-Noise Ratio",
    description: "Relates the signal-to-quantization-noise ratio of a uniform PCM system with the number of bits allocated per sample.",
    module: 4
  },
  {
    id: "friis-formula",
    name: "Friis Formula for Noise Factor",
    equation: "F_total = F₁ + (F₂ - 1)/G₁ + (F₃ - 1)/(G₁G₂)",
    variables: "F_n = Noise factor of stage n, G_n = Power gain of stage n",
    description: "Calculates the overall noise factor of a multi-stage cascaded receiver amplifier chain, highlighting that the first stage dominates overall noise performance.",
    module: 5
  },
  {
    id: "thermal-noise",
    name: "Thermal Noise Power",
    equation: "P_n = k * T * B",
    variables: "P_n = Noise power (W), k = Boltzmann's constant (1.38e-23 J/K), T = Absolute Temperature (K), B = Bandwidth (Hz)",
    description: "Quantifies the electric noise generated by the thermal agitation of charges inside an electrical conductor.",
    module: 5
  }
];

export const bec402Papers: ExamPaper[] = [
  {
    id: "bec402-model-1",
    title: "Fourth Semester B.E. Degree Examination (Model Paper-1)",
    period: "Model Paper 1 (CBCS)",
    subjectCode: "BEC402",
    subjectName: "Principles of Communication Systems",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing at least ONE question from each MODULE.",
      "M : Marks, L : Bloom's Level, C : Course Outcomes."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define Probability. Illustrate the relationship between sample space, events and probability.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Define the autocorrelation and cross-relation functions. Infer the properties of autocorrelation function.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Develop a MATLAB/Python script to generate the probability density function (PDF) of a Gaussian distribution function and plot it.",
              marks: 8,
              level: "L3",
              co: "CO5"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is conditional probability? Prove that P(B/A) = [P(A/B) * P(B)] / P(A).",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Outline random processes and illustrate an ensemble of sample functions with a neat diagram.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Show that, if a stationary Gaussian process X(t) is applied to a stable linear time-invariant filter, then the output random process Y(t) is also a Gaussian process.",
              marks: 8,
              level: "L3",
              co: "CO5"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "Interpret the concepts of modulation index and percentage of modulation. Write the necessary equations for Amplitude Modulation (AM).",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "A standard AM broadcast station is allowed to transmit modulating frequencies upto 5 KHz. If the AM station is transmitting on a frequency of 980 KHz, compute the maximum and minimum upper and lower sidebands and the total bandwidth occupied by the AM station.",
              marks: 5,
              level: "L3",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Explain the high-level collector modulator circuit with a neat, properly labeled block diagram.",
              marks: 7,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "Outline an AM diode detector demodulator with a neat schematic circuit diagram and output filtering waveforms.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "An AM transmitter has a carrier power of 30 W. The percentage of modulation is 85 percent (μ = 0.85). Calculate (i) the total transmitted power and (ii) the power contained in one of the sidebands.",
              marks: 5,
              level: "L3",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Explain the general block diagram of a Frequency Division Multiplexing (FDM) scheme in both transmitter and receiver ends.",
              marks: 7,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "Compare and contrast Frequency Modulation (FM) and Amplitude Modulation (AM) across bandwidth, noise immunity, efficiency, and application areas.",
              marks: 6,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explore with a neat schematic diagram how frequency modulation is realized using an Integrated Circuit Voltage Controlled Oscillator (IC VCO).",
              marks: 7,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Draw the block diagram of a superheterodyne receiver and explain the role of RF stage, Mixer, IF amplifier, and detector blocks in detail.",
              marks: 7,
              level: "L2",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "Identify a hardware configuration method used to convert a phase-modulated (PM) signal into a frequency-modulated (FM) signal using an integrator.",
              marks: 6,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Define Phase Locked Loop (PLL). Explain the basic block diagram of a PLL along with absolute capture and lock range definitions.",
              marks: 7,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Interpret the concept of an RF Mixer circuit with a neat schematic block diagram showing incoming RF, local oscillator LO, and combined IF products.",
              marks: 7,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "What are the core technical advantages of digital communication signal transmission formats over traditional analog systems?",
              marks: 4,
              level: "L1",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "State the Nyquist sampling theorem. Explain the flat-top sampling technique with neat sketches and equations, detailing aperture effect and its reconstruction challenges.",
              marks: 10,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain the generation and detection of Pulse Position Modulation (PPM) waves using block diagrams of monostable multivibrators.",
              marks: 6,
              level: "L2",
              co: "CO3"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is the Aperture Effect in Pulse Amplitude Modulation (PAM) systems? Outline how updating reconstruction filters with equalizers minimizes this issue.",
              marks: 4,
              level: "L1",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "What is multiplexing and why is it required in digital circuits? Explain the structural working of Time Division Multiplexing (TDM) with commutator block diagrams.",
              marks: 10,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain the primary functional elements of a Pulse Code Modulation (PCM) system with neat sketches (Sampler, Quantizer, Encoder).",
              marks: 6,
              level: "L3",
              co: "CO3"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define Intersymbol Interference (ISI). Outline a baseband binary data transmission system model using clear block diagrams and impulse response equations.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Develop a MATLAB/Python script to model an eye diagram representing noise margins, timing jitter, and peak distortion.",
              marks: 6,
              level: "L3",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Illustrate the concept of noise factor in cascaded amplifier stages. Write down Friis' formula and define each parameter clearly.",
              marks: 6,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the following concepts briefly: (i) Nyquist criterion for distortionless baseband transmission. (ii) Baseband M-ary PAM transmission limitations.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Develop a scripting routine to generate waveform layouts for NRZ (Non-Return-to-Zero) and RZ (Return-to-Zero) signaling streams.",
              marks: 0, // Wait, page 2 lists marks 06. Let's make it 6.
              level: "L3",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Define Signal-to-Noise Ratio (SNR). Explain the differences between external (environmental) and internal (thermal, shot) noise sources.",
              marks: 6,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      }
    ]
  },
  {
    id: "bec402-model-2",
    title: "Fourth Semester B.E. Degree Examination (Model Paper-2)",
    period: "Model Paper 2 (CBCS)",
    subjectCode: "BEC402",
    subjectName: "Principles of Communication Systems",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing at least ONE question from each MODULE.",
      "M : Marks, L : Bloom's Level."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "A random variable is said to be uniformly distributed over the interval (a,b). Determine the probability density function (PDF) of a uniformly distributed RV.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Determine the characteristic function of a Gaussian random variable with given mean μ and variance σ².",
              marks: 8,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Prove the following properties of the Autocorrelation Function (ACF) of a stationary random process:\ni) If X(t) contains a constant DC component equal to A, then Rx(τ) contains a constant value of A².\nii) If X(t) contains a sinusoidal component, its ACF also contains a cosine wave of the same frequency.",
              marks: 6,
              level: "L2",
              co: "CO5"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define random process parameters: Correlation, Covariance, and Correlation Coefficient.",
              marks: 4,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Explain the Central Limit Theorem (CLT) and explain why it makes Gaussian processes omnipresent in communication noise analysis.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Define Autocorrelation and Cross-correlation functions. State and verify the essential mathematical properties of Autocorrelation.",
              marks: 8,
              level: "L3",
              co: "CO5"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain amplitude modulation in the time domain and frequency domain. Provide expressions and sideband spectrum illustrations.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "With a block schematic of a square-law modulator circuit and current-voltage characteristics, explain the generation of AM.",
              marks: 5,
              level: "L3",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Develop a scripting routine to simulate Amplitude Modulation (AM) and envelope demodulation, then display the resulting sideband frequency spectrum.",
              marks: 7,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "An AM transmitter uses high-level modulation of the final RF amplifier, which has a DC supply voltage V_cc of 48 V and draws total current of 3.5 A. Assuming amplifier efficiency is 70 percent:\na) Determine the total RF input power to the final class C stage.\nb) Find the audio frequency power required to achieve a modulation index (μ) of 1.0.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Explain with neat circuit schematics the operation of a practical AM envelope detector using a diode receiver.",
              marks: 5,
              level: "L3",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Explain with balanced circuit diagrams the construction and operation of a lattice-type ring modulator.",
              marks: 7,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "An FM receiver experiences a signal-to-noise ratio (S/N) of 2.8 at its RF front-end. The audio modulating frequency is 1.5 kHz and max peak frequency deviation is 4 kHz. Calculate:\na) The equivalent frequency deviation caused by the noise.\nb) The improved SNR ratio available at the demodulated audio output.",
              marks: 6,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explain the mathematical spectrum representation of a single-tone FM wave in terms of Bessel functions J_n(β). Draw the sideband amplitude profile.",
              marks: 7,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Explain how direct frequency modulation is realized using a crystal oscillator stabilized varactor diode tuning structure.",
              marks: 7,
              level: "L2",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "Examine the noise suppression effect of wideband frequency modulation (the threshold effect and capture ratio).",
              marks: 6,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Compare and contrast FM generation using stable crystal oscillator circuits against varactor-driven voltage variable reactors.",
              marks: 7,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Describe the general block diagram of a superheterodyne front-end receiver, and analyze why tuning intermediate frequency (IF) stabilizes performance.",
              marks: 7,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define the Flat-Top Sampling theorem. Prove that sampling a continuous signal is equivalent to shifting its spectrum to multiples of the sampling frequency.",
              marks: 4,
              level: "L1",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "For the binary data stream [01101001], draw the exact structural waveforms for:\ni) Unipolar NRZ\nii) Polar NRZ\niii) Unipolar RZ\niv) Bipolar AMI (RZ)\nv) Manchester encoding",
              marks: 10,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain PPM wave generation from a PWM baseline inside monostable circuits, with block diagrams.",
              marks: 6,
              level: "L2",
              co: "CO3"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is the aperture effect in PAM systems? Detail how a flat-top pulse duration introduces roll-off and how equalizers resolve this.",
              marks: 4,
              level: "L1",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "What is multiplexing? Explain how Time Division Multiplexing (TDM) samples multiple incoming signals sequentially through a commutator switch.",
              marks: 10,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Describe the design calculations and Nyquist requirements for typical PCM pulse filters (Review of textbook problems 7.3, 7.4, 7.14, and 7.17 on signal reconstruction bandwidth).",
              marks: 6,
              level: "L3",
              co: "CO3"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is Intersymbol Interference (ISI)? Outline a baseband digital receiver system using an equivalent channel model with pulse shaping filters.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Develop a scripting routine to simulate transmission paths and display eye diagram configurations on screen.",
              marks: 6,
              level: "L3",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Explain the bandwidth calculations and spectral efficiency of standard T1 carrier multiplexed digital telephone hierarchies.",
              marks: 6,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the following concepts briefly:\ni) Nyquist's pulse criteria for distortionless transmission.\nii) Baseband M-ary PAM signaling configurations.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Develop coding blocks to create NRZ-L, NRZ-M, and RZ waves from arbitrary numeric input sequences.",
              marks: 6,
              level: "L3",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "State the origins of electronic noise. Distinguish between external man-made static emissions and internal noise sources like Thermal and Shot processes.",
              marks: 6,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      }
    ]
  },
  {
    id: "bec402-dec24-jan25",
    title: "Fourth Semester B.E./B.Tech. Degree Examination",
    period: "Dec.2024/Jan.2025",
    subjectCode: "BEC402",
    subjectName: "Principles of Communication Systems",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing ONE full question from each module.",
      "M : Marks, L : Bloom's Level."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define probability. Illustrate the relationship between sample space, events and probability.",
              marks: 6,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Outline random processes and illustrate an ensemble of sample functions with a neat diagram.",
              marks: 6,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Show that if a Gaussian process X(t) is applied to a stable linear filter, then the random process Y(t) developed at the output of the filter is also Gaussian.",
              marks: 8,
              level: "L3",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is conditional probability? Prove Bayes theorem representing: P(B/A) = [P(A/B) * P(B)] / P(A).",
              marks: 6,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Define basic Statistical Parameters of random distributions: Mean, Autocorrelation, and Covariance functions.",
              marks: 6,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Develop a functional code script to plot standard Gaussian probability density functions given different variance configurations.",
              marks: 8,
              level: "L3",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "An antenna has a load impedance of 40 Ω. If an unmodulated AM transmitter outputs 4.8 A RF current, and gets modulated at 90 percent (μ = 0.90), calculate:\ni) The baseline Carrier Power (P_c)\nii) The Total Transmitted Power (P_t)\niii) The combined Sideband Power output (P_sb)",
              marks: 6,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Describe amplitude demodulation using a diode envelope detector. Detail the choice of RC time constant to avoid diagonal clipping.",
              marks: 7,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Explain a general block diagram of an FDM (Frequency Division Multiplexing) transmission scheme.",
              marks: 7,
              level: "L1",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "Interpret the concepts of modulation index and percentage of AM modulation. Write down the voltage equations for double-sideband full-carrier AM.",
              marks: 6,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Explain high level collector modulation of RF Class C amplifiers with the aid of structured block schematics.",
              marks: 7,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Describe with schematic diagrams the signal balancing and carrier cancellation in an AM Lattice Ring Modulator.",
              marks: 7,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "Compare and contrast Frequency Modulation (FM) and Amplitude Modulation (AM) across spectral profiles and noise performance.",
              marks: 6,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Explain with schematic diagrams the operation of frequency modulation realized using voltage-controlled multivibrators (IC VCO).",
              marks: 7,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Explain the general block schematic of a superheterodyne communication receiver, showing intermediate frequency downconversion.",
              marks: 7,
              level: "L2",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "The input to an FM demodulator has a carrier-to-noise ratio (CNR) of 2.8. If the audio band is 1.5 kHz and peak deviation is 4 kHz, find:\na) Equivalent noise frequency deviation.\nb) The improvement factor in output signal-to-noise ratio.",
              marks: 6,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Define Phase Locked Loop (PLL). Explain the basic block diagram of a PLL, describing the phase detector and VCO.",
              marks: 7,
              level: "L1",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Describe JFET active mixer circuit behaviors, outlining why square-law characteristics reduce intermodulation.",
              marks: 7,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "Detail the critical advantages of digital symbols and pulse transmission over analog propagation.",
              marks: 4,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Explain the essential elements of a Pulse Code Modulation (PCM) system with structured block diagrams (L.P. filter, Sampler, Quantizer, Encoder).",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "For the binary pattern [01101001], map the electrical signaling levels for:\ni) Unipolar NRZ\nii) Polar NRZ\niii) Unipolar RZ\niv) Manchester code",
              marks: 8,
              level: "L3",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "State and prove the Shannon Whittaker sampling theorem, illustrating spectral recovery via Low Pass Filter convolution.",
              marks: 4,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "What is multiplexing and why is it required? Explain Time Division Multiplexing (TDM) using commutator block layouts.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Describe the generation and recovery of Pulse Position Modulated (PPM) signals using timing diagrams.",
              marks: 8,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define Intersymbol Interference (ISI). Describe a baseband binary data transmission model using impulse shapes and Nyquist's ideal criterion.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Develop a scripting code routine to simulate NRZ pulses and filter them to construct clean RZ output transitions.",
              marks: 4,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Explain Signal-to-Noise Ratio (SNR) in cascaded communication devices. Discuss external thermal noise vs internal atomic noise in receivers.",
              marks: 8,
              level: "L2",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the following system concepts briefly:\ni) Nyquist criterion for distortionless baseband transmission.\nii) Baseband M-ary PAM symbol rates and bandwidth requirements.",
              marks: 8,
              level: "L1",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Develop a scripting routine to plot a Raised Cosine filter frequency response showing different roll-off factors α.",
              marks: 4,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Illustrate the concept of noise factor in cascaded networks. Write the Friis transmission amplifier formula and define all terms.",
              marks: 8,
              level: "L2",
              co: "CO3"
            }
          ]
        }
      }
    ]
  },
  {
    id: "bec402-june24",
    title: "Fourth Semester B.E./B.Tech. Degree Examination",
    period: "June/July 2024",
    subjectCode: "BEC402",
    subjectName: "Principles of Communication Systems",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing ONE full question from each module.",
      "M : Marks, L : Bloom's Level."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is conditional probability? Prove that if A and B are independent events, P(A ∩ B) = P(A) * P(B).",
              marks: 5,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Define the autocorrelation function of a random process. Discuss its properties (mean square value, symmetry, upper bounds) in detail.",
              marks: 10,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Develop a program to generate Gaussian random distribution waves and show that its distribution fits a bell curve.",
              marks: 5,
              level: "L3",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define auto-covariance, cross-covariance, and joint stationarity of random processes.",
              marks: 8,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "A random variable has a PDF given by f(x) = C * e^{-2x} for x ≥ 0. Find (i) constant C, (ii) probability that it lies between 1 and 3.",
              marks: 4,
              level: "L3",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Discuss the properties of Gaussian random variables and explain the Q-function as applied to bit error calculation.",
              marks: 8,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain double sideband suppressed carrier (DSB-SC) amplitude modulation. Derive its time domain equations and show its spectrum sketches.",
              marks: 8,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Define modulation index. Explain why overmodulation (μ > 1) causes envelope distortion in diode detectors.",
              marks: 6,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Derive the mathematical expression for Amplitude Modulated (AM) power distribution into carrier and sidebands.",
              marks: 6,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain a general block diagram of an FDM (Frequency Division Multiplexing) system with carrier sub-channel configurations.",
              marks: 6,
              level: "L1",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explain the working principle of a lattice ring modulator for DSB-SC generation, and show how diode switches alternate carrier phases.",
              marks: 7,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Explain AM demodulation using active collectors and diode envelopes, highlighting diagonal filtering solutions.",
              marks: 7,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "Convert a phase modulated wave into an FM format using a circuit diagram containing an integrator.",
              marks: 7,
              level: "L1",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Determine the FM spectrum and bandwidth using Carson's rule. If peak deviation is 5 kHz and audio modulating signal is 1 kHz, find total B_w.",
              marks: 6,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Identify the noise suppression properties of FM. Contrast wideband FM noise margins against AM envelope formats.",
              marks: 7,
              level: "L2",
              co: "CO3"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "With a block diagram, explain the operation of a superheterodyne receiver front end, from RF antenna tuning to audio demodulation.",
              marks: 8,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Define Phase Locked Loop. Explain circuit elements of an IC 565 PLL for frequency demodulation.",
              marks: 8,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain the working principle of a Frequency-Modulator using a Voltage Controlled Oscillator (NE566).",
              marks: 4,
              level: "L2",
              co: "CO3"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "Why digitize analog waveforms? Analyze the advantages of PCM and noise margins over pure analog systems.",
              marks: 6,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "What is quantization noise? Derive the expression of quantization SNR for a uniform quantizer in linear and decibel systems.",
              marks: 7,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Explain Time Division Multiplexing (TDM) using commutators and detail slot synchronization techniques.",
              marks: 7,
              level: "L2",
              co: "CO4"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "State and prove the Whittaker-Shannon sampling theorem, showing how a bandlimited wave can be retrieved from sampled lines.",
              marks: 6,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "For the binary stream [01101001], draw line codes for: (i) Unipolar NRZ, (ii) Polar NRZ, (iii) Unipolar RZ, (iv) Bipolar AMI, (v) Manchester, (vi) Differential Coding.",
              marks: 9,
              level: "L3",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Explain the generation and reception of Pulse Position Modulation (PPM) with monostable triggers and waveforms.",
              marks: 5,
              level: "L2",
              co: "CO4"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "Develop a scripting routine to simulate an eye diagram and detail how timing noise maps to horizontal eye closure.",
              marks: 6,
              level: "L3",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Explain the concept of thermal and shot noise. Derive equations for noise temperature and equivalent cascade noise profiles.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Define Intersymbol Interference. Outline the baseband transmission model using channel frequency response plots.",
              marks: 8,
              level: "L1",
              co: "CO5"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain bandwidth requirements and slot structures for the standard baseband T1 digital carrier system.",
              marks: 6,
              level: "L1",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Write short notes on: (i) Signal to Noise ratio, (ii) External atmospheric noise, (iii) Internally generated semiconductor noise.",
              marks: 8,
              level: "L1",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "An RF amplifier has an S/N ratio of 8 at its input and an S/N ratio of 6 at its output. Calculate its Noise Factor (F) and Noise Temperature (T_e).",
              marks: 6,
              level: "L3",
              co: "CO5"
            }
          ]
        }
      }
    ]
  },
  {
    id: "bec402-june25",
    title: "Fourth Semester B.E./B.Tech. Degree Examination",
    period: "June/July 2025",
    subjectCode: "BEC402",
    subjectName: "Principles of Communication Systems",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing ONE full question from each module.",
      "M : Marks, L : Bloom's Level."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define Probability. Illustrate the relationship between sample space, events and probability.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "What are random variable moments? Determine the characteristic function of a Gaussian random variable with given mean and variance.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Analyze the Gaussian process with a Gaussian distribution curve. Infer why stable filters maintain Gaussian outputs.",
              marks: 8,
              level: "L2",
              co: "CO5"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define a random process. Interpret joint stationarity and covariance parameters across sample sets.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "What is the Autocorrelation function? State and prove the boundaries and symmetry properties of ACF.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Analyze the probability density function (PDF) and cumulative distribution function (CDF) of a random experiment where a coin is tossed three times.",
              marks: 8,
              level: "L3",
              co: "CO5"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define Amplitude Modulation. Derive the modulation index and envelope voltage equations in the time domain.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "A standard AM broadcast station is allowed to transmit modulating frequencies up to 5 KHz. If the AM station is transmitting on a frequency of 980 KHz, compute sidebands and bandwidth.",
              marks: 5,
              level: "L3",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Outline the block diagram of an FDM (Frequency Division Multiplexing) transmitter. Discuss the applications of FDM.",
              marks: 7,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "Develop a scripting layout to generate Amplitude Modulation waveforms and display sideband spectra dynamically.",
              marks: 8,
              level: "L3",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Apply the concept of sidebands to explain Double Sideband Suppressed Carrier (DSB-SC) and Single Sideband (SSB) techniques.",
              marks: 5,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Explain with diagrams the working principle of a lattice-type balanced ring modulator.",
              marks: 7,
              level: "L2",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "Identify a circuit configuration to convert a Phase Modulated (PM) wave into a frequency-modulated (FM) wave.",
              marks: 6,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "An FM receiver experiences S/N = 2.8 at input. The modulating wave is 1.5 kHz and deviation is 4 kHz. Find equivalent noise deviation and output SNR.",
              marks: 6,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Interpret with a neat circuit schematic diagram the frequency modulation generated using varactor-tuned voltage controlled crystal oscillators (VVC).",
              marks: 8,
              level: "L2",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define frequency modulation index β. Identify any five differences between Frequency Modulation (FM) and Amplitude Modulation (AM).",
              marks: 6,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Why are pre-emphasis and de-emphasis stages required in FM broadcast networks? Explain their time constants and circuits.",
              marks: 6,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Draw the block diagram of a superheterodyne receiver and explain the detailed function and gains of each stage.",
              marks: 8,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "State and prove flat top sampling theorem. Outline standard reconstruction methods of low pass signals.",
              marks: 10,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Infer the functional elements and working of a thermal Time Division Multiplexing (TDM) system with commutator switches.",
              marks: 5,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain briefly the functional block diagram of a Waveform PPM (Pulse Position Modulation) generator.",
              marks: 5,
              level: "L2",
              co: "CO3"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "Identify and explain the basic elements of a PCM system with neat diagrams (Sampler, Quantizer, Encoder).",
              marks: 10,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "For the binary stream [01101001], draw line coding wave patterns for:\n(i) Unipolar NRZ\n(ii) Polar NRZ\n(iii) Unipolar RZ\n(iv) Bipolar AMI RZ\n(v) Manchester format",
              marks: 5,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain briefly the mid-tread and mid-rise uniform Quantizers with respective input-output step waveforms.",
              marks: 5,
              level: "L2",
              co: "CO3"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is Intersymbol Interference? Describe equivalent baseband transmission paths with neat block structures.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Define Signal-to-Noise Ratio. Summarize different classes of external man-made noise vs internal semiconductor thermal noise.",
              marks: 7,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Illustrate the active concept of electrical noise in cascaded stages. Write Friis formula and state all gain and noise factors.",
              marks: 5,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is baseband digital transmission? Explain the following concepts briefly:\n(i) Nyquist criterion for distortionless transmission.\n(ii) Baseband M-ary PAM signaling rates.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Define thermal noise voltage equation. Describe method to generate and plot Raised Cosine filter wave response.",
              marks: 7,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "What is Noise Factor? What is Noise Figure? An amplifier stage with gain G = 15 dB has input SNR of 10 dB and output SNR of 7 dB. Find stage Noise Figure.",
              marks: 5,
              level: "L2",
              co: "CO4"
            }
          ]
        }
      }
    ]
  },
  {
    id: "bec402-makeup-jun25",
    title: "Fourth Semester B.E./B.Tech. Degree Examination (Make-Up Exam)",
    period: "June/July 2025 (Makeup)",
    subjectCode: "BEC402",
    subjectName: "Principles of Communication Systems",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing ONE full question from each module.",
      "M : Marks, L : Bloom's Level."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define the Autocorrelation and Cross-correlation functions. Discuss the analytical properties of ACF of random signals.",
              marks: 10,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Define probability. Illustrate the relationship between sample space, events, and axiomatic probability rules.",
              marks: 5,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Develop a software routine to plot standard Gaussian probability densities with mean zero for different variances.",
              marks: 5,
              level: "L3",
              co: "CO5"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain Conditional Probability. Prove the Bayes theorem representing structural dependencies P(B/A) = [P(A/B) * P(B)] / P(A).",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Explain the Central Limit Theorem (CLT) as applied to a large ensemble of independent Gaussian Random Processes.",
              marks: 6,
              level: "L2",
              co: "CO5"
            },
            {
              subNumber: "c",
              text: "Verify the properties of ACF of Gaussian stationary processes, including upper bounds and DC components.",
              marks: 8,
              level: "L3",
              co: "CO5"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "Write a MATLAB/Python routine to generate AM signaling waveforms in time domain and display the sideband spectrum on screen.",
              marks: 8,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explain the working principle of a lattice ring modulator for DSB-SC creation, highlighting the diode switching sequence.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "An AM wire has carrier power of 30W. If modulated at 85 percent (μ = 0.85), find total power P_t and power in single sideband P_sb.",
              marks: 4,
              level: "L3",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain how amplitude modulated AM signal is demodulated using a simple diode detector circuit schematic.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explain the working of an active Demodulator/Receiver for Frequency Division Multiplexed (FDM) systems.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Explain disadvantages of Double Sideband DSB-Full Carrier compared to Single Sideband (SSB) in terms of bandwidth and power efficiency.",
              marks: 4,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define Phase Locked Loop (PLL). Explain with a neat block schematic the capture and lock operation of IC PLL 565 units.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explain the demodulation of frequency modulated FM signals using an envelope detector combined with a frequency slope discriminator.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "An FM wave has modulating frequency f_m = 5kHz and deviation frequency deviation Δf = 30kHz. Calculate Carson's bandwidth and modulation index β.",
              marks: 4,
              level: "L3",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "Draw the block diagram of a superheterodyne receiver and explain the detailed function and selectivity of the IF stage.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explain FM noise suppression effects, detailing how high carrier powers reduce thermal audio threshold limits.",
              marks: 6,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Compare Amplitude Modulation (AM) vs Frequency Modulation (FM) on power efficiency and operational signal bandwidths.",
              marks: 6,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is quantization? Derive the signal-to-quantization-noise ratio (SNR)_0 representing uniform quantizers:\n(SNR)₀ = [3 * P] / (m_max)² * 2^(2R)",
              marks: 10,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Explain the regeneration of PCM (Pulse Code Modulation) waves along wire paths with a neat block diagram of regenerative repeaters.",
              marks: 5,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain important core advantages of digital signals (robustness to noise, encryption, regeneration) over analog transmission lines.",
              marks: 5,
              level: "L2",
              co: "CO3"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the generation and detection of Pulse Position Modulation (PPM) waves, drawing neat timing diagrams.",
              marks: 10,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "An analog signal is specified by the equations:\ni) x(t) = 3 * cos(50πt) + 10 * sin(300πt) + cos(100πt)\nii) x(t) = [1 / 2π] * cos(4000πt) * cos(1000πt)\nDetermine the minimum Nyquist sampling rates required for each signal.",
              marks: 10,
              level: "L3",
              co: "CO3"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define Intersymbol Interference (ISI). Explain baseband binary data transmission systems with beat block (duobinary/Nyquist) diagrams and math equations.",
              marks: 10,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Explain different types of external environmental disturbances vs internally generated atomic (thermal, shot) noise.",
              marks: 5,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Write a note on the structure and information revealed by an Eye Diagram (noise margin, timing sensitivity, distortion).",
              marks: 5,
              level: "L2",
              co: "CO4"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain Nyquist pulse shaping criteria and frequency response limits for baseband digital data transmission channels.",
              marks: 12,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "With a neat circuit block diagram, explain cascade stages noise factor. Derive the Friis noise amplification formula and define terms.",
              marks: 8,
              level: "L2",
              co: "CO4"
            }
          ]
        }
      }
    ]
  }
];
