/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ExamPaper } from './types.ts';

export interface MicrocontrollersFormula {
  id: string;
  name: string;
  equation: string;
  variables: string;
  description: string;
  module: number;
}

export const bec405aFormulas: MicrocontrollersFormula[] = [
  {
    id: "baud-rate-timer1-mode2",
    name: "8051 Serial Baud Rate (Timer 1, Mode 2)",
    equation: "Baud Rate = (2^SMOD / 32) * (XTAL / (12 * (256 - TH1)))",
    variables: "SMOD = Double baud rate bit (0 or 1), XTAL = Crystal frequency (usually 11.0592 MHz), TH1 = Timer 1 high byte reload value",
    description: "Calculates the serial transmission baud rate generated by reload values of Timer 1 in 8-bit auto-reload mode.",
    module: 3
  },
  {
    id: "timer-clock-machine-cycles",
    name: "8051 Machine Cycle Frequency & Period",
    equation: "f_MC = XTAL / 12  |  T_MC = 1 / f_MC = 12 / XTAL",
    variables: "XTAL = Crystal frequency. For 11.0592 MHz, T_MC = 1.085 μs. For 22 MHz, T_MC = 545.45 ns.",
    description: "Computes the duration of a single instruction machine cycle, which serves as the clock source for all internal timers.",
    module: 3
  },
  {
    id: "timer-delay-ticks",
    name: "Timer Reload Value (16-bit Mode 1)",
    equation: "N_ticks = Required Delay / T_MC  |  Reload = 65536 - N_ticks",
    variables: "T_MC = Machine cycle time, N_ticks = Number of counts required. Value is split into THx and TLx bytes.",
    description: "Determines the start count value (THx, TLx) loaded into 8051 timers to generate an exact time delay or square wave frequency.",
    module: 3
  },
  {
    id: "timer-delay-ticks-mode2",
    name: "Timer Reload Value (8-bit Auto-Reload Mode 2)",
    equation: "N_ticks = Required Delay / T_MC  |  Reload (THx) = 256 - N_ticks",
    variables: "T_MC = Machine cycle time, N_ticks = Number of counts (must be <= 256)",
    description: "Determines the auto-reload value loaded into the THx register of Timer 0/1 to achieve dynamic high-frequency intervals.",
    module: 3
  },
  {
    id: "address-decoding-range",
    name: "Memory Mapping & Address Decoding Range",
    equation: "Addr Range = Base Address to (Base Address + Size - 1)",
    variables: "Base Address = Hex code indicating chip select activation, Size = Memory capacity in bytes (e.g., 8KB = 0x2000, 16KB = 0x4000)",
    description: "Relates microcontroller port lines (like P0, P2, latch ALE, read PSEN) to external chip select ranges for EPROM and RAM chips.",
    module: 1
  }
];

export const bec405aPapers: ExamPaper[] = [
  {
    id: "bec405a-dec-2024-jan-2025",
    title: "Fourth Semester B.E./B.Tech. Degree Examination",
    period: "Dec.2024/Jan.2025",
    subjectCode: "BEC405A",
    subjectName: "Microcontrollers",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing ONE full question from each module.",
      "M : Marks, L : Bloom's level, C : Course outcomes.",
      "Support programs with block diagrams or flowcharts."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "Bring out the differences between a Microprocessor and a Microcontroller based on architecture, internal peripherals, cost, and typical user applications.",
              marks: 4,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "With function of each pin, explain the layout of 8051 Microcontroller. Clarify alternative functions of Port 3 pins.",
              marks: 10,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Summarize the internal RAM memory configuration of 8051 microcontroller. Distinguish among Working Registers, Bit-Addressable space, and General Purpose RAM.",
              marks: 6,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "Differentiate between CISC (Complex Instruction Set Computer) and RISC (Reduced Instruction Set Computer) architectures.",
              marks: 4,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "With a neat schematic block diagram, explain the internal hardware architectural features of the 8051 microcontroller.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Interface an 8051 microcontroller to 16K bytes of external EPROM (Program Memory) and 8K bytes of external data RAM. Explain clearly with a schematic showing address/data connections and chip selects (use ALE, PSEN, RD, WR).",
              marks: 8,
              level: "L3",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "What is an addressing mode? Explain the 4 different addressing modes of the 8051 microcontroller with two Assembly instruction examples for each.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Illustrate with a neat flowchart or coordinate diagram the physical ranges and boundaries of Relative (SJMP), Absolute (AJMP), and Long (LJMP) jump instructions.",
              marks: 6,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Write an 8051 Assembly Language Program (ALP) to convert a packed BCD number loaded in memory into two separate ASCII numbers. Store the unpacked upper and lower digits in registers R5 and R6 respectively.",
              marks: 6,
              level: "L2",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "Define assembler directives inside 8051 Assembly language. Explain the usage of ORG, DB, EQU, and END with code fragments.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "List and explain bit-level logical instructions (SETB, CLR, CPL, ANL, ORL) available inside the 8051 microcontroller.",
              marks: 6,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Develop an ALP to swap the byte contents of register R3 and R4 registers in Register Bank 0 using at least three different coding methods.",
              marks: 6,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the complete bit structures and default configurations of the TCON (Timer Control) and TMOD (Timer Mode) registers.",
              marks: 6,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Develop an Assembly program to generate a continuous square wave of frequency 1 kHz on Port Pin P1.2 using Timer 0 in 8-bit auto-reload mode (Mode 2). Show complete machine-tick mathematical calculations. Assume the XTAL frequency is 22 MHz.",
              marks: 6,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain RS232 standard serial communication signal lines. Show how 8051 is interfaced to RS232 using a MAX232 level-converter chip and standard DB-9 pin connector.",
              marks: 8,
              level: "L3",
              co: "CO3"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the bit pattern of SCON (Serial Control) register with a block diagram describing transmit/receive modes.",
              marks: 4,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Develop an 8051 C language program to transfer the ASCII letter \"A\" serially at a 9600 baud rate, with 8-bit data and 1 stop bit, continuously. Show TH1 initialization calculations under a standard 11.0592 MHz crystal.",
              marks: 8,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Explain Mode 2 (8-bit auto-reload) timer operations. List the steps required to program Timer 0 in Mode 2 to generate accurate microsecond delays as a software module.",
              marks: 8,
              level: "L2",
              co: "CO3"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the structure and bit patterns of the IP (Interrupt Priority) and IE (Interrupt Enable) SFR registers in 8051.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Recall and describe the Interrupt Vector Table (IVT) of 8051 Microcomputer. List vector locations, interrupt sources and priority defaults.",
              marks: 6,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Explain the programming steps to enable and handle multiple interrupts at once in 8051. Clarify how the hardware resolves concurrent hits on INT0 and Serial Interrupt.",
              marks: 6,
              level: "L2",
              co: "CO4"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "List and trace the chronologic hardware steps execution that take place within 8051 CPU when an external interrupt request is acknowledged.",
              marks: 4,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Write an Assembly Language Program utilizing interrupts to generate a 10 kHz square wave on pin P1.2 using Timer 0 in Mode 2, while concurrently performing a byte transfer from Port 0 to Port 2 in the main background loop. XTAL = 22 MHz.",
              marks: 8,
              level: "L3",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Explain the microsecond-accurate steps involved inside 8051 serial ISR to receive blocks of packets. Support your description with code segment loops.",
              marks: 8,
              level: "L2",
              co: "CO4"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "With a neat circuit schematic diagram, write an 8051 C program to interface an R-2R DAC (Digital-to-Analog Converter) chip to generate a continuous Staircase output waveform having exactly 20 equal voltage steps.",
              marks: 10,
              level: "L3",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Explain the hardware interface setup and corresponding C software modules to control the rotational speed and direction of a standard DC Motor from the 8051 pins using an H-Bridge driver L293D.",
              marks: 10,
              level: "L3",
              co: "CO5"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "With a neat connection schematic, write an 8051 C program to interface a 4-coil Stepper Motor to Port 1 of the 8051 microcontroller. Implement step rotations in half-step excitation sequence.",
              marks: 10,
              level: "L3",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Write an 8051 C language program to display the text string \"HELLO WORLD\" on a standard 16x2 character LCD display interfaced to 8051 pins. Include necessary delays and cmd write/data write routines.",
              marks: 10,
              level: "L3",
              co: "CO5"
            }
          ]
        }
      }
    ]
  },
  {
    id: "bec405a-june-july-2024",
    title: "Fourth Semester B.E. Degree Examination",
    period: "June/July 2024",
    subjectCode: "BEC405A",
    subjectName: "8051 Microcontroller",
    scheme: "CBCS Scheme",
    timeStr: "3 hrs.",
    maxMarks: 100,
    instructions: [
      "Answer any FIVE full questions, choosing ONE full question from each module.",
      "M : Marks, L : Bloom's level, C : Course outcomes."
    ],
    modules: [
      {
        moduleNumber: 1,
        primary: {
          number: 1,
          subQuestions: [
            {
              subNumber: "a",
              text: "Bring out the functional differences between Microprocessors and Microcontrollers. Compare resources such as registers, caches, stack limits and bus controls.",
              marks: 5,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Differentiate between CISC and RISC instruction processing speeds, addressing complexities and pipeline steps helper cycles.",
              marks: 5,
              level: "L1",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "With neat modular configuration diagrams, explain the architectural layout of internal Rom, Ram and accumulator structures inside 8051 core.",
              marks: 10,
              level: "L2",
              co: "CO1"
            }
          ]
        },
        alternative: {
          number: 2,
          subQuestions: [
            {
              subNumber: "a",
              text: "With neat diagram, explain 8051 Microcontroller internal memory registers, RAM layout, and special SFR spaces.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "b",
              text: "Write an interfacing diagram of 8051 microcontroller configured with 8k bytes of external RAM and 8k bytes of external EPROM. Outline calculations of active high/low chips select ranges.",
              marks: 8,
              level: "L2",
              co: "CO1"
            },
            {
              subNumber: "c",
              text: "Write standard technical criteria for selecting microcontrollers for an embedded product (speed, packaging, power, I/O lines, and cost).",
              marks: 4,
              level: "L1",
              co: "CO1"
            }
          ]
        }
      },
      {
        moduleNumber: 2,
        primary: {
          number: 3,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the address calculation and coding for 5 addressing modes in 8051 Assembly. Give simple code syntax for each.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Write an ALP to multiply two 16-bit numbers loaded from external ROM memory and store the 32-bit product in consecutive scratch registers.",
              marks: 8,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Write an ALP to convert a standard packed BCD byte to two ASCII code elements packing them into registers R5 and R6.",
              marks: 4,
              level: "L3",
              co: "CO2"
            }
          ]
        },
        alternative: {
          number: 4,
          subQuestions: [
            {
              subNumber: "a",
              text: "Write an assembly programming block to add two sixteen-bit data blocks loaded in R1-R0 and R3-R2. Store result to register targets.",
              marks: 8,
              level: "L3",
              co: "CO2"
            },
            {
              subNumber: "b",
              text: "Explain the hardware implementation of instructions: DJNZ Rn, Label; JNC Label; and DA A.",
              marks: 8,
              level: "L2",
              co: "CO2"
            },
            {
              subNumber: "c",
              text: "Explain with examples logical assembly actions: SWAP, XCH, RLC, and Movx.",
              marks: 4,
              level: "L2",
              co: "CO2"
            }
          ]
        }
      },
      {
        moduleNumber: 3,
        primary: {
          number: 5,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain Mode 2 operation of 8051 timers. Detail timer configuration steps using Assembly to program Timer 0 in Mode 2.",
              marks: 8,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Set up the complete register map of TMOD. Analyze the TCON Interrupt Flags behaviors under software queries.",
              marks: 8,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Show connections and pins to connect an 8051 RS232 communications model with DB-9 pin connectors.",
              marks: 4,
              level: "L1",
              co: "CO3"
            }
          ]
        },
        alternative: {
          number: 6,
          subQuestions: [
            {
              subNumber: "a",
              text: "Write an 8051 C program to continuously transmit the message \"YES\" serially at 9600 baud rate, with 8-bit characters and 1 stop bit. XTAL = 11.0592 MHz.",
              marks: 8,
              level: "L3",
              co: "CO3"
            },
            {
              subNumber: "b",
              text: "Explain the bit structures of TCON (Timer Control) register. List functions of each bit in tracking pulse edges.",
              marks: 8,
              level: "L2",
              co: "CO3"
            },
            {
              subNumber: "c",
              text: "Compare Simplex, Half-Duplex, and Full-Duplex serial modes. Describe serial data transmission frames.",
              marks: 4,
              level: "L1",
              co: "CO3"
            }
          ]
        }
      },
      {
        moduleNumber: 4,
        primary: {
          number: 7,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain the structure of Interrupt priority SFR and Interrupt enable register in 8051. How do we mask external interrupts?",
              marks: 6,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Write 8051 code elements executing an interrupt-driven serial buffer read process. State the priority resolution rules.",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Explain the mechanism of level-triggered vs edge-triggered external interrupts inside the 8051 core.",
              marks: 6,
              level: "L2",
              co: "CO4"
            }
          ]
        },
        alternative: {
          number: 8,
          subQuestions: [
            {
              subNumber: "a",
              text: "Explain step execution in servicing an interrupt. What registers are saved automatically on the stack?",
              marks: 8,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "b",
              text: "Formulate the interrupt vector table of the 8051 microcontroller. State vector address targets for INT0, TF0, INT1, TF1, RI/TI.",
              marks: 6,
              level: "L2",
              co: "CO4"
            },
            {
              subNumber: "c",
              text: "Write a program illustrating nested interrupts implementation, with two priorities handling external signals on pins.",
              marks: 6,
              level: "L2",
              co: "CO4"
            }
          ]
        }
      },
      {
        moduleNumber: 5,
        primary: {
          number: 9,
          subQuestions: [
            {
              subNumber: "a",
              text: "With dual wiring registers description, draft an 8051 C program to control a stepper motor rotation interfacing driver chips.",
              marks: 10,
              level: "L3",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Develop an 8051 C programming interface showing connections and code to spin a DC motor continuously.",
              marks: 10,
              level: "L3",
              co: "CO5"
            }
          ]
        },
        alternative: {
          number: 10,
          subQuestions: [
            {
              subNumber: "a",
              text: "With a detailed wiring diagram, write an 8051 C program to control standard key-row matrix scanners or display LCD units.",
              marks: 10,
              level: "L3",
              co: "CO5"
            },
            {
              subNumber: "b",
              text: "Interface 8051 pins with a DAC0808 converter chip. Write an 8051 C speed controller code to generate staircase waveforms.",
              marks: 10,
              level: "L3",
              co: "CO5"
            }
          ]
        }
      }
    ]
  }
];
